version: 0.2
phases:
  build:
    commands:
      - set -e
      - echo "Uploading index.html with no-cache headers to s3://$BUCKET"
      - aws s3 cp index.html s3://$BUCKET/index.html --cache-control "no-cache, no-store, must-revalidate" --content-type "text/html"
      - echo "Uploading versioned CSS with long cache headers"
      - aws s3 cp . s3://$BUCKET/ --recursive --exclude "*" --include "styles.css" --cache-control "public, max-age=31536000, immutable" --content-type "text/css"
      - echo "Uploading versioned JS with long cache headers"
      - aws s3 cp . s3://$BUCKET/ --recursive --exclude "*" --include "scripts.js" --cache-control "public, max-age=31536000, immutable" --content-type "application/javascript"
artifacts:
  files:
    - '**/*'
